
baseURL = "https://eitanoid.com/"
title = ""
theme = "hugo-blog-awesome"

name = 'Eitan'
bio = 'Mathematician, computer and coffee enthusiast.'

# This is what goes in <html lang="">
languageCode = "en-us"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

enableEmoji = true

[params]
	monoDarkIcon = true # show monochrome dark mode icon
	math = true         # enable KaTeX math typesetting globally
	goToTop = true      # enable go to top button in posts
	toc = true # enable table of contents globally
	tocOpen = false # close toc by default

[params.author]
  intro = "Personal Blog"
  name = "Eitan"
  description = "My personal blog to document and showcase my interest in mathematics, computer science, programming and coffee."

[[params.socialIcons]]
name = "github"
url = "https://github.com/eitanoid"

# [[params.socialIcons]]
# name = "linkedin"
# url = ""

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[markup]
	[markup.highlight]
		noClasses = false          # set markup.highlight.noClasses=false to enable code highlight
	[markup.goldmark.renderer]
		unsafe = true              # needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
	[markup.tableOfContents]
		startLevel = 2             # ToC starts from H2
		endLevel = 4               # ToC ends at H4
		ordered = false            # generates <ul> instead of <ol>

[menu]
  [[menu.main]]
    identifier = ""
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "reading-list"
    name = "Reading"
    url = "/reading-list/"
    weight = 4

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

