
baseURL = "https://eitanoid.com/"
languageCode = "en-us"
title = ""
theme = "paper"

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  github = 'eitanoid'                 # github.com/YOUR_GITHUB_ID
  # linkedin = 'eitan-ostashinski'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Eitan'
  bio = 'Mathematician, computer and coffee enthusiast.'

  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = ""
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "math"
    name = "Maths"
    url = "/math/"
    weight = 3

  [[menu.main]]
    identifier = "reading-list"
    name = "Reading"
    url = "/reading-list/"
    weight = 4

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 5


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

